# Generated by Django 2.2.7 on 2019-11-24 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('fio_author', models.CharField(max_length=100)),
                ('number_of_pages', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=50)),
                ('house_number', models.CharField(max_length=10)),
                ('apartment_number', models.IntegerField()),
                ('pasport', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_library.Book')),
                ('reader_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_library.Reader')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='section_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_library.Section'),
        ),
    ]
